### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by szepeshazi** [nullEuro/python-irtoy#1] opened 2013-09-30 04:15 UTC
I'm trying to use your package on a Synology DS713+ NAS. I have python3 and pyserial installed on my device. When I try to run your application, I get this:
./irtoy.py --help
Traceback (most recent call last):
  File "./irtoy.py", line 5, in <module>
    from lib import irtoy, ir
  File "/xxxx/irtoy-python/python-irtoy-master/lib/irtoy.py", line 13
    DataEnd=                     bytes.fromhex(u'ff ff'),
                                     ^
SyntaxError: invalid syntax
Do you have any tips how to resolve this? Thanks

**Comment by nullEuro** [comment] 2013-09-30 11:48
Hm... cannot reproduce this. Which version of python3 are you running? `python3 --version`
Maybe something messed the files up, can you try a fresh clone/download?
The first 15 lines of the corrupt file would also be interesting: `head lib/irtoy.py  -n 15`

**Edit:** After some further investigation I discovered that the error occurs when using an older version of python 3 (<=3.3). Fixed with commit ab17893ed1ded51267b8e1f213cc45d92ad604a2, please re-download/git pull. Thanks for reporting!

**Closed as completed** 2013-09-30 12:20 UTC
Labels: bug
